### ISSUE TITLE
Document 'sidebar-search-bs.html' is now `search-field.html` and other PyData theme changes

### ISSUE THREAD

**Issue by fmaussion** [executablebooks/sphinx-book-theme#329]
After the last update to `0.1.0`, our builds on ReadTheDocs started to fail ([full log](https://readthedocs.org/projects/oggm-edu/builds/13629587/)):

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/oggm-edu/conda/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oggm-edu/conda/latest/lib/python3.9/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/oggm-edu/conda/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/oggm-edu/conda/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oggm-edu/conda/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 534, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/oggm-edu/conda/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 544, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oggm-edu/conda/latest/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 611, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oggm-edu/conda/latest/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1061, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page activity_sheets/as_gallery.
Reason: TemplateNotFound('sidebar-search-bs.html')

Theme error:
An error happened in rendering the page activity_sheets/as_gallery.
Reason: TemplateNotFound('sidebar-search-bs.html')
```

Our environment:https://github.com/OGGM/oggm-edu/blob/master/docs/environment.yml

our conf file: https://github.com/OGGM/oggm-edu/blob/master/docs/conf.py

Pinning back to `sphinx-book-theme==0.0.42` solved the issue. 

Maybe related to https://github.com/pydata/pydata-sphinx-theme/issues/320, I'm not sure.

**Comment by fmaussion** [comment]
Note that we are using this feature here:

```python
html_sidebars = {
    "**": ["sidebar-search-bs.html", "sbt-sidebar-nav.html", "sbt-sidebar-footer.html"]
}
```

Which is still documented as working at https://sphinx-book-theme.readthedocs.io/en/latest/configure.html?highlight=sidebar-search-bs.html#default-sidebar-elements?

**Comment by choldgraf** [comment]
Ah good catch - the field should now be called `search-field.html` I believe, we need to update the documentation!

**Comment by NiklasBeierl** [comment]
I am using `sphinx-book-theme = "0.1.0"` and set `language = 'de'` in my `conf.py`.

The onyl thing which is not being translated on the built html site is this text on the search page: (search.html) 
```
    Searching for multiple words only shows matches that contain
    all words.
```
Is that also addressed here, or should I open another ticket?
