### ISSUE TITLE
TemplateNotFound: sidebar-logo.html

### ISSUE THREAD

**Issue by aladinoster** [executablebooks/sphinx-book-theme#421]
### Describe the problem

Hello, 
Thanks for developing `sphinx-book-theme`. I used former versions and recently after updating my environment. When trying to create the documentation for this project [symupy](https://github.com/licit-lab/symupy). 

One can recreate the conda environment via `conda create -f docs/requirments.doc.yaml` + `pip install -r requirements.txt` (only unix systems for the moment)
 
```
Traceback (most recent call last):
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1055, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx_book_theme/layout.html", line 7, in top-level template code
    {%- set sidebar_width_class = "col-md-3" %}
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx_book_theme/../pydata_sphinx_theme/layout.html", line 10, in top-level template code
    <a class='right-next' id="next-link" href="{{ next.link|e }}" title="{{ _('next page')}}">{{ next_title or next.title }}</a>
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/themes/basic/../basic/layout.html", line 169, in top-level template code
    {%- block content %}
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx_book_theme/../pydata_sphinx_theme/layout.html", line 57, in block 'content'
    {% block docs_sidebar %}
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx_book_theme/layout.html", line 14, in block 'docs_sidebar'
    {% include "sidebar.html" %}
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx_book_theme/sidebar.html", line 2, in top-level template code
    {%- include sidebartemplate %}
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/jinja2glue.py", line 217, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sidebar-logo.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 531, in write
    self._write_serial(sorted(docnames))
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 541, in _write_serial
    self.write_doc(docname, doctree)
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 632, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/Users/andresladino/opt/anaconda3/envs/symupy-doc/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1062, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page README.
Reason: TemplateNotFound('sidebar-logo.html')
```

### Steps to reproduce

`git clone https://github.com/licit-lab/symupy.git`
`cd symupy`
`conda create -f docs/requirments.doc.yaml`
`pip install -r requirements.txt` 
`make docs` 

### The version of Python you're using

3.9

### Your operating system

OS X

### Versions of your packages

```
# packages in environment at /Users/andresladino/opt/anaconda3/envs/symupy-doc:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appnope                   0.1.2            py39h6e9494a_1    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
boost                     1.74.0           py39ha641261_3    conda-forge
boost-cpp                 1.74.0               hbdcdab7_3    conda-forge
brotlipy                  0.7.0           py39h89e85a6_1001    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.0               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cairo                     1.16.0            he43a7df_1008    conda-forge
certifi                   2021.10.8        py39h6e9494a_0    conda-forge
cffi                      1.14.6           py39he338e87_1    conda-forge
cfitsio                   3.470                h01dc385_7    conda-forge
chardet                   4.0.0            py39h6e9494a_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
coverage                  6.0.2            py39h89e85a6_0    conda-forge
cryptography              35.0.0           py39h209aa08_1    conda-forge
curl                      7.79.1               hf45b732_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               ha13b53f_2    conda-forge
debugpy                   1.4.1            py39h9fcab8e_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docutils                  0.16             py39h6e9494a_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                he49afe7_0    conda-forge
fontconfig                2.13.1            h10f422b_1005    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.6                h0d85af4_0    conda-forge
future                    0.18.2           py39h6e9494a_3    conda-forge
geos                      3.9.1                he49afe7_2    conda-forge
geotiff                   1.6.0                hba2ba3e_5    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.70.0               hcf210ce_1    conda-forge
glib-tools                2.70.0               hcf210ce_1    conda-forge
greenlet                  1.1.2            py39h9fcab8e_0    conda-forge
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        4.8.1            py39h6e9494a_0    conda-forge
importlib_resources       3.3.1            py39h6e9494a_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipykernel                 6.4.2            py39h71a6800_0    conda-forge
ipython                   7.28.0           py39h71a6800_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py39h6e9494a_2    conda-forge
jinja2                    3.0.2              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.15                 hcb556a6_0    conda-forge
jsonschema                4.1.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.0            py39h6e9494a_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kealib                    1.4.14               h31dd65d_2    conda-forge
kiwisolver                1.3.2            py39hf018cea_0    conda-forge
krb5                      1.19.2               hcfbf3a7_2    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
libblas                   3.9.0           12_osx64_openblas    conda-forge
libcblas                  3.9.0           12_osx64_openblas    conda-forge
libclang                  11.1.0          default_he082bbe_1    conda-forge
libcurl                   7.79.1               hf45b732_1    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libdap4                   3.20.6               h3e144a0_2    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                he49afe7_4    conda-forge
libgdal                   3.2.1                h6de91e5_9    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.0               hf1fb8c0_1    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8fd9edb_1014    conda-forge
liblapack                 3.9.0           12_osx64_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_2    conda-forge
libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
libnghttp2                1.43.0               h6f36284_1    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     13.3                 hea3049e_1    conda-forge
librttopo                 1.1.0                h5413771_6    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libspatialite             5.0.1                heb715ac_4    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.2.0                h46d1c8c_2    conda-forge
libwebp-base              1.2.1                h0d85af4_0    conda-forge
libxml2                   2.9.12               h93ec3fd_0    conda-forge
libxslt                   1.1.33               h5739fc3_2    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
lxml                      4.6.3            py39hf41e7f8_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
markupsafe                2.0.1            py39h89e85a6_0    conda-forge
matplotlib                3.4.3            py39h6e9494a_1    conda-forge
matplotlib-base           3.4.3            py39hb07454d_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h89e85a6_1004    conda-forge
more-itertools            8.10.0             pyhd8ed1ab_0    conda-forge
mysql-common              8.0.25               h694c41f_0    conda-forge
mysql-libs                8.0.25               h54f5a68_0    conda-forge
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.2.0            py39h6e9494a_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nbsphinx                  0.8.7              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nspr                      4.30                 hcd9eead_0    conda-forge
nss                       3.69                 h31e2bf1_1    conda-forge
numpy                     1.21.3           py39h7eed0ac_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.4            py39h4d6be9b_0    conda-forge
pandoc                    2.15                 h0d85af4_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.2.0            py39h5fdd921_1    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
pluggy                    1.0.0            py39h6e9494a_1    conda-forge
poppler                   21.03.0              h640f9a4_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                13.3                 he8fe76e_1    conda-forge
proj                      8.0.0                h1512c50_0    conda-forge
prompt-toolkit            3.0.21             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydata-sphinx-theme       0.6.3              pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.1              pyhd8ed1ab_1    conda-forge
pyqt                      5.12.3           py39h6e9494a_7    conda-forge
pyqt5                     5.15.5                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyqtchart                 5.12             py39hef7122c_7    conda-forge
pyqtgraph                 0.12.3             pyhd8ed1ab_0    conda-forge
pyqtwebengine             5.12.1           py39hef7122c_7    conda-forge
pyrsistent                0.17.3           py39h89e85a6_2    conda-forge
pysocks                   1.7.1            py39h6e9494a_3    conda-forge
pytest                    6.2.5            py39h6e9494a_0    conda-forge
python                    3.9.7           h1248fe1_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-decouple           3.4                pyhd3deb0d_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h89e85a6_0    conda-forge
pyzmq                     22.3.0           py39h7fec2f1_0    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
rapidjson                 1.1.0             hb1e8313_1002    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scipy                     1.7.1            py39h056f1c0_0    conda-forge
setuptools                58.2.0           py39h6e9494a_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sphinx                    4.2.0              pyh6c4a22f_0    conda-forge
sphinx-book-theme         0.1.6              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.26           py39h89e85a6_0    conda-forge
sqlite                    3.36.0               h23a322b_2    conda-forge
symucore                  1.0.0                         0    licit-lab
symuflow                  1.0.0            py39ha5a8b8e_0    licit-lab
symupy                    0.5.1                     dev_0    <develop>
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tiledb                    2.2.9                he9a4fb4_0    conda-forge
tk                        8.6.11               h5dbffcc_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.2.2              pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h89e85a6_1    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
tzcode                    2021e                h0d85af4_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unixodbc                  2.3.9                hd863c23_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.3                h379762d_3    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xqilla                    2.3.4                         0    licit-lab
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.4.9                h582d3a0_0    conda-forge
```

**Comment by goekce** [comment]
I had a similar problem. I wanted to setup the extensions automatically using `requirements.txt` like this:
```python
with open('requirements.txt') as f:
    extensions = [
        line.strip()
        for line in f.readlines()
    ]
```
`sphinx_book_theme` must not be loaded using `extensions`. So I modified to:
```python
with open('requirements.txt') as f:
    extensions = [
        line.strip()
        for line in f.readlines()
        if line.strip() != 'sphinx_book_theme'
    ]
```
