### ISSUE TITLE
Issue in building the project on https://readthedocs.org/projects/

### ISSUE THREAD

**Issue by krai7921** [executablebooks/sphinx-book-theme#555]
When i am trying to build the project on https://readthedocs.org/projects/

Below error i am getting 

/home/docs/checkouts/readthedocs.org/user_builds/soc-dms-new/envs/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Running Sphinx v4.5.0
loading translations [en]... done
making output directory... done
WARNING: html_static_path entry '_static' does not exist

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/soc-dms-new/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/soc-dms-new/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 256, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/soc-dms-new/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 314, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/soc-dms-new/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 212, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/soc-dms-new/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 260, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/soc-dms-new/envs/latest/lib/python3.7/site-packages/sphinx/theming.py", line 241, in create
    raise ThemeError(__('no theme named %r found (missing theme.conf?)') % name)
sphinx.errors.ThemeError: no theme named 'sphinx_book_theme' found (missing theme.conf?)

**Theme error:
no theme named 'sphinx_book_theme' found (missing theme.conf?)**

**Comment by choldgraf** [comment]
It looks like you need to install the theme in readthedocs. For example, here's a blog post describing how to use conda to install things with readthedocs:

https://zonca.dev/2020/05/readthedocs-conda.html

I'll close this, as I believe it is not related to this theme specifically, but is a RTD configuration issue.
