### ISSUE TITLE
0.3.3: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [executablebooks/sphinx-book-theme#590]
### Describe the bug

Looks like documentation build fails on sphinx 5.x.
There are as well some warnings.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.2
making output directory... done
checking bibtex cache... out of date
parsing bibtex file /home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/references.bib... parsed 2 entries
myst v0.17.2: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'colon_fence'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, sub_delimiters=('{', '}'), words_per_minute=200)
WARNING: 'jupyter_execute_notebooks' is deprecated for 'nb_execution_mode' [mystnb.config]
WARNING: 'execution_show_tb' is deprecated for 'nb_execution_show_tb' [mystnb.config]
myst-nb v0.15.0: NbParserConfig(custom_formats={}, metadata_key='mystnb', cell_metadata_key='mystnb', kernel_rgx_aliases={}, execution_mode='cache', execution_cache_path='', execution_excludepatterns=(), execution_timeout=30, execution_in_temp=False, execution_allow_errors=False, execution_raise_on_error=False, execution_show_tb=False, merge_streams=False, render_plugin='default', remove_code_source=False, remove_code_outputs=False, number_source_lines=False, output_stderr='show', render_text_lexer='myst-ansi', render_error_lexer='ipythontb', render_image_options={}, render_figure_options={}, render_markdown_format='commonmark', output_folder='build', append_css=True, metadata_to_fm=False)
Using jupyter-cache at: /home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/build/sphinx/.jupyter_cache
[autosummary] generating autosummary for: changelog.md, content-blocks.md, contributing/architecture.md, contributing/index.md, contributing/setup.md, contributing/style.md, contributing/subthemes.md, contributing/tests.md, contributing/translate.md, customize/announcements.md, ..., reference/comments.md, reference/extensions.md, reference/kitchen-sink/api.rst, reference/kitchen-sink/index.rst, reference/kitchen-sink/lists-and-tables.rst, reference/kitchen-sink/paragraph-markup.rst, reference/notebooks.md, reference/special-theme-elements.md, reference/thebe.md, tutorials/get-started.md
loading intersphinx inventory from https://docs.python.org/3.8/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 35 added, 0 changed, 0 removed
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/content-blocks.md: Executing notebook using local CWD [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/content-blocks.md: Executed notebook in 1.21 seconds [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/content-blocks.md: Cached executed notebook: ID=1 [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/notebooks.md: Executing notebook using local CWD [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/notebooks.md: Executing notebook using local CWD [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/special-theme-elements.md: Executing notebook using local CWD [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/special-theme-elements.md: Executed notebook in 2.61 seconds [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/special-theme-elements.md: Cached executed notebook: ID=2 [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/thebe.md: Executing notebook using local CWD [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/thebe.md: Executed notebook in 1.38 seconds [mystnb]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/thebe.md: Cached executed notebook: ID=3 [mystnb]
reading sources... [100%] tutorials/get-started
https://i3.ytimg.com/vi/2Z7wDaYt53Y/maxresdefault.jpg -> /home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/build/sphinx/man/_video_thumbnail/2Z7wDaYt53Y.jpg (downloading)

/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/content-blocks.md:148: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/content-blocks.md:220: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/content-blocks.md:226: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/contributing/setup.md:42: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/launch.md:21: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/notebooks.md: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/notebooks.md:104: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/notebooks.md: WARNING: Notebook exception traceback saved in: /home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/build/sphinx/man/reports/notebooks.err.log [mystnb.exec]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/api.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/lists-and-tables.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/paragraph-markup.rst.rst:229: WARNING: line number spec is out of range(1-10): '5-15'
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/paragraph-markup.rst:260: WARNING: Footnote [4] is not referenced.
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/paragraph-markup.rst:266: WARNING: Footnote [11] is not referenced.
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/paragraph-markup.rst:17: ERROR: Undefined substitution referenced: "problematic".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/paragraph-markup.rst:260: ERROR: Unknown target name: "5".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/paragraph-markup.rst:303: ERROR: Unknown target name: "body elements".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/paragraph-markup.rst:315: ERROR: Unknown target name: "hyperlink reference without a target".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/notebooks.md: WARNING: Executing notebook failed: CellExecutionError [mystnb.exec]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/notebooks.md: WARNING: Notebook exception traceback saved in: /home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/build/sphinx/man/reports/reference/notebooks.err.log [mystnb.exec]
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/special-theme-elements.md:143: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/special-theme-elements.md:151: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/special-theme-elements.md:160: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/special-theme-elements.md:171: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/special-theme-elements.md:199: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/tutorials/get-started.md:108: ERROR: Unknown directive type "margin".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... sphinxbooktheme.1 { tutorials/get-started customize/index customize/sidebar-primary customize/sidebar-secondary customize/announcements customize/header customize/download customize/source-files customize/custom-css customize/single-page content-blocks notebooks launch contributing/index contributing/setup contributing/architecture contributing/style contributing/tests contributing/translate contributing/subthemes reference/kitchen-sink/index reference/kitchen-sink/paragraph-markup reference/kitchen-sink/api reference/kitchen-sink/lists-and-tables reference/special-theme-elements reference/extensions reference/notebooks reference/thebe reference/blog reference/api-numpy reference/comments changelog } /home/tkloczko/rpmbuild/BUILD/sphinx-book-theme-0.3.3/docs/reference/kitchen-sink/paragraph-markup.rst:26: WARNING: py:class reference target not found: test_py_module.test.Foo
/usr/lib64/python3.8/asyncio/events.py:docstring of asyncio.events.AbstractEventLoop.create_datagram_endpoint:17: WARNING: py:data reference target not found: socket.SO_REUSEPORT
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.array:75: WARNING: py:obj reference target not found: empty_like
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.array:77: WARNING: py:obj reference target not found: ones_like
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.array:79: WARNING: py:obj reference target not found: zeros_like
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.array:81: WARNING: py:obj reference target not found: full_like
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.array:83: WARNING: py:obj reference target not found: empty
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.array:85: WARNING: py:obj reference target not found: ones
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.array:87: WARNING: py:obj reference target not found: zeros
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.array:89: WARNING: py:obj reference target not found: full
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.transpose:35: WARNING: py:obj reference target not found: ndarray.transpose
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.transpose:37: WARNING: py:obj reference target not found: moveaxis
/usr/lib64/python3.8/site-packages/numpy/__init__.py:docstring of numpy.transpose:39: WARNING: py:obj reference target not found: argsort
failed

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 517, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 98, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 29, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 122, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 347, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 347, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
The full traceback has been saved in /tmp/sphinx-err-vlu1ukph.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@devel-g2v SPECS]$ cat /tmp/sphinx-err-vlu1ukph.log
# Sphinx version: 5.0.2
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:
#   reference/special-theme-elements
#   reference/extensions
#   reference/notebooks
#   reference/thebe
#   reference/blog
#   reference/api-numpy
#   reference/comments
#   changelog
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   ablog (0.10.26) from /usr/lib/python3.8/site-packages/ablog/__init__.py
#   sphinx_togglebutton (0.3.2) from /usr/lib/python3.8/site-packages/sphinx_togglebutton/__init__.py
#   myst_nb (0.15.0) from /usr/lib/python3.8/site-packages/myst_nb/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   numpydoc (1.4.0) from /usr/lib/python3.8/site-packages/numpydoc/__init__.py
#   sphinx.ext.intersphinx (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinxcontrib.youtube (unknown version) from /usr/lib/python3.8/site-packages/sphinxcontrib/youtube/__init__.py
#   sphinx_copybutton (0.5.0) from /usr/lib/python3.8/site-packages/sphinx_copybutton/__init__.py
#   sphinx_design (0.2.0) from /usr/lib/python3.8/site-packages/sphinx_design/__init__.py
#   sphinx_examples (0.0.5) from /usr/lib/python3.8/site-packages/sphinx_examples/__init__.py
#   sphinx_tabs.tabs (unknown version) from /usr/lib/python3.8/site-packages/sphinx_tabs/tabs.py
#   sphinx_thebe (0.1.2) from /usr/lib/python3.8/site-packages/sphinx_thebe/__init__.py
#   sphinxcontrib.bibtex (2.4.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/bibtex/__init__.py
#   sphinxext.opengraph (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/opengraph/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 517, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 98, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 29, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 122, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 347, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
```

### Reproduce the bug

Run `sphinx-build -n -T -b man docs build/sphinx/man` in project root directory

### List your environment

```console
Package                       Version
----------------------------- -----------------
ablog                         0.10.26
alabaster                     0.7.12
appdirs                       1.4.4
asttokens                     2.0.5
attrs                         22.1.0.dev0
Babel                         2.10.2
backcall                      0.2.0
Brlapi                        0.8.3
build                         0.8.0
charset-normalizer            2.1.0
click                         8.1.2
codespell                     2.1.0
commonmark                    0.9.1
cssselect                     1.1.0
cycler                        0.11.0
debugpy                       1.6.2
decorator                     5.1.1
distro                        1.7.0
docutils                      0.17.1
entrypoints                   0.4
executing                     0.8.3
extended-project              1.2.3
extras                        1.0.0
fastjsonschema                2.15.3
feedgen                       0.9.0
fixtures                      4.0.0
fonttools                     4.34.4
gpg                           1.17.1-unknown
greenlet                      1.1.2
idna                          3.3
imagesize                     1.4.1
importlib-metadata            4.12.0
importlib-resources           5.8.0
iniconfig                     1.1.1
invoke                        1.7.0
ipykernel                     6.15.1
ipython                       8.4.0
jedi                          0.18.1
Jinja2                        3.1.1
jsonschema                    4.7.2
jupyter-cache                 0.5.0
jupyter-client                7.3.4
jupyter-core                  4.11.1
kiwisolver                    1.4.4
latexcodec                    2.0.1
libcomps                      0.1.18
louis                         3.22.0
lxml                          4.9.1
markdown-it-py                2.1.0
MarkupSafe                    2.1.1
matplotlib                    3.5.2
matplotlib-inline             0.1.3
mdit-py-plugins               0.3.0
mdurl                         0.1.1
myst-nb                       0.15.0
myst-parser                   0.17.2
nbclient                      0.6.6
nbformat                      5.4.0
nest-asyncio                  1.5.5
nodeenv                       1.7.0
numpy                         1.23.1
numpydoc                      1.4.0
olefile                       0.46
packaging                     21.3
parso                         0.8.3
pbr                           5.8.1
pep517                        0.12.0
pep621                        0.4.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.0.4
pluggy                        1.0.0
prompt-toolkit                3.0.29
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pybtex                        0.24.0
pybtex-docutils               1.0.1
Pygments                      2.12.0
PyGObject                     3.42.1
pyparsing                     3.0.9
pyrsistent                    0.18.1
pytest                        7.1.2
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
pyzmq                         23.2.0
requests                      2.28.1
rich                          12.5.0
rpm                           4.17.0
scour                         0.38.2
setuptools                    63.2.0
simple-project                1.2.3
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        5.0.2
sphinx-copybutton             0.5.0
sphinx_design                 0.2.0
sphinx-examples               0.0.5
sphinx-tabs                   3.4.1
sphinx-thebe                  0.1.2
sphinx-theme-builder          0.2.0a14
sphinx-togglebutton           0.3.2
sphinxcontrib-applehelp       1.0.2.dev20220714
sphinxcontrib-bibtex          2.4.2
sphinxcontrib-devhelp         1.0.2.dev20220714
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220712
sphinxcontrib-qthelp          1.0.3.dev20220712
sphinxcontrib-serializinghtml 1.1.5
sphinxcontrib-youtube         1.1.0
sphinxext-opengraph           0.6.3
SQLAlchemy                    1.4.39.dev0
stack-data                    0.3.0
tabulate                      0.8.9
testtools                     2.5.0
tomli                         2.0.1
tornado                       6.1
traitlets                     5.3.0
typing_extensions             4.2.0
urllib3                       1.26.9
watchdog                      2.1.9
wcwidth                       0.2.5
wheel                         0.37.1
zipp                          3.8.1
```

**Comment by choldgraf** [comment]
Just a note that I don't believe this theme yet supports Sphinx 5:

https://github.com/executablebooks/sphinx-book-theme/blob/443c7a7167cc39bffa4b41079e6db96490cf98af/pyproject.toml#L24-L28

**Comment by choldgraf** [comment]
Closed by:

- https://github.com/executablebooks/sphinx-book-theme/pull/644
