### ISSUE TITLE
pydata-sphinx-theme 0.13.2 breaks sphinx-book-theme

### ISSUE THREAD

**Issue by jakevdp** [executablebooks/sphinx-book-theme#711]
### Describe the bug

After pydata-sphinx-theme updated to 0.13.2, our sphinx-build job in http://github.com/google/jax showed the following error:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 262, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 334, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 248, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 299, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/theming.py", line 232, in create
    self.load_extra_theme(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/theming.py", line 177, in load_extra_theme
    self.load_external_theme(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/theming.py", line 202, in load_external_theme
    self.app.registry.load_extension(self.app, entry_point.module)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/registry.py", line 462, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx_book_theme (exception: cannot import name '_get_theme_options' from 'pydata_sphinx_theme' (/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/pydata_sphinx_theme/__init__.py))
```
We are pinning to `pydata-sphinx-theme==0.13.1` for the time being to fix the error.

- Our requirements file is here: https://github.com/google/jax/blob/main/docs/requirements.txt
- Our readthedocs config is here: https://github.com/google/jax/blob/main/.readthedocs.yml

The breaking change in pydata-sphinx-theme seems to be this one: https://github.com/pydata/pydata-sphinx-theme/commit/fc975d0737a6096dcadd783128027aa4469e7261

I'm reporting here because it looks like sphinx-book-theme is using an API that is intended to be private.

**Comment by AakashGfude** [comment]
Hi @jakevdp, thank you for raising this. Your comments are on point. We will follow your advice and fix this soon.

**Comment by jakevdp** [comment]
It looks like pydata-sphinx-theme 0.13.3 has a new public method, `pydata_sphinx_theme.utils.sphinx_book_theme_dict`. The fix I think would be to pin `pydata-sphinx-theme>=0.13.3` and use that new public API.
